name: ⚡ My ci things

on: [push]

jobs:
  my-workflow:
    name: 📣 Generate cool badges
    runs-on: ubuntu-latest
    steps:
      # Necessary to push the generated badges to the repo
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
