name: ⚡ My ci things

on: [push]

jobs:
  my-workflow:
    name: 📣 Generate cool badges
    runs-on: ubuntu-latest
    steps:
      # Necessary to push the generated badges to the repo
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      # ...

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🔍 Tests
        run: yarn test-ci

      - name: ⚙️ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
